### ISSUE TITLE
Momentary ETA option

### ISSUE THREAD

**Issue by a-j-wood** [a-j-wood/pv#14]
From Luc Gommans in 2016; summary of correspondence is below

[lgommans.diff.txt](https://github.com/a-j-wood/pv/files/8793389/lgommans.diff.txt)

Hello Andrew,

First of all, thanks for all the work on pv so far, it's a great tool!

The ETA is currently always based on the average transfer speed since
the program was started. For some purposes it's more useful to use the
current transfer speed, so I added an option to enable this. The code is
available on Github:

https://github.com/lgommans/pv

The option is named "meta" for "momentary ETA" (like "fineta" is for
"finish ETA") and the short option is "-m". I think the word "current"
("ceta" or "cureta") might have been more clear, also because "meta" is
an English word, but the "-c" option is already in use for another feature.

I don't know which version control system you use, but your website
mentions patches can be sent via the contact form (and in turn the
contact form mentions the PGP key I am emailing to). If it's more
convenient for you, I could generate a patch instead of linking to the
repository. In that case, let me know which command I should use to
generate the patch (on Debian if possible).

The Github repository contains the updated changelog, NEWS, man page,
and of course code. I did everything I thought necessary for a release;
hopefully I didn't forget anything (and hopefully I wasn't too
overbearing in choosing a new version number and adding my own name to
the changelog).

Please let me know whether you find the feature useful enough to release
and, if so, whether I forgot anything to make a release possible.

Kind regards,
Luc

---
 
Date: Sun, 28 Aug 2016 16:31:31 +0100                                                                                                              
From: Andrew Wood
To: Luc
Subject: Re: Contributing a feature for pv: use current speed for ETA                                                                              

Thanks for your email.  I will hopefully have some time to look at your
changes later today.  It sounds like a useful feature.

I use an offline Subversion repository for development so I will just run
"diff" between the latest released version and your changed version to see
your updates.

My only concern with you publishing your version on Github is that it might
lead to confusion.  But the README on the page is very clear about where the
official version can be found so that's OK.

Thanks again and I will write back in a day or two.

----

Date: Wed, 31 Aug 2016 00:41:20 +0100                                                                                                              
From: Andrew Wood
To: Luc
Subject: Re: Contributing a feature for pv: use current speed for ETA                                                                              

I've had a look at your code and it looks fine.  The only thing missing is a
format string specifier for your new option (in pv__format_init) so it
wouldn't work with "-F" / "--format".  That's no problem, I will put that
in.

I will probably rename the option since "meta", being an English word, is a
confusing name for it.  Unfortunately all the names I can think of at the
moment are worse, though less ambiguous.  Something like "momentary-eta"
will probably do.

Is it OK to mention your name and web site (https://lgms.nl/) in the
acknowledgements section of the documentation?

----

Date: Wed, 31 Aug 2016 16:25:22 +0300
From: Luc
To: Andrew Wood
Subject: Re: Contributing a feature for pv: use current speed for ETA

Yes, in fact I'd like to be mentioned in acknowledgements, with my full
name and that domain if possible.

Other options for momentary-eta (a long option called like that is
kinda... long) might be instant-eta, noavg-eta, current-eta... It would
be nice if the short option matches the long one, but it could
technically be a random letter (you could pick the least-most common
first letter in English perhaps, to leave space for other options in the
future). Just ideas.

Thanks again!

Luc Gommans

**Comment by a-j-wood** [comment]
@lgommans this is superseded by pull request #65, so I will close this - thanks again for your patch.

**Comment by lgommans** [comment]
Thanks!

Btw it looks like I used the wrong sending address at some point, would you mind removing my email address from the first comment here? I think it's also possible to remove a revision from the post history. (I'm surprised I haven't gotten spam on that address yet actually, since it's been here since 2022!)

**Comment by a-j-wood** [comment]
Sure, I have edited the first post.
