### ISSUE TITLE
No output in Arch Linux initcpio after 1.6.6

### ISSUE THREAD

**Issue by a-j-wood** [a-j-wood/pv#19]
Correspondence summary:

hi,

here are two screenshots : no change with the additional parameters (I used /dev/urandom instead of /dev/zero).

![2022 02 01-10 39 48](https://user-images.githubusercontent.com/89565849/170873750-1f7f2fde-122b-4232-8104-55dded797574.png)

![2022 02 01-10 43 26](https://user-images.githubusercontent.com/89565849/170873753-4ffbdbe0-d29f-454a-bf34-c4027d700ddd.png)

the tests are here done with qemu but the operation is identical with a
real machine.
qemu -kernel archkernel -initrd myinitcpio.pv.1.6.20
qemu -kernel archkernel -initrd myinitcpio.pv.1.6.6
regards, lacsaP.

Le lun. 31 janv. 2022 à 23:32, Andrew Wood a écrit :

> Hello, thanks for your email.
>
> Do you know what happens if you use "-f" with pv in this case?
>
> Also does "-L 500" make any difference?
>
> Wondering if either terminal detection or rate of output changes the
> outcome.
>
> > Sent from: lacsaP
> >
> > hi,
> > have a look here : https://bugs.archlinux.org/task/73393
> > regards, lacsaP.

**Comment by patatetom** [comment]
hi,

a small remark on this subject:
the use of `pv` is done very early in the initrd and `/dev/stderr` is not available at that time (archlinux).
I realized this in one of my scripts that did not display in the console the error message sent to `/dev/stderr` (the file `/dev/stderr` was created instead, so no error was reported).
on the other hand, the redirection to fd#2 works.
```
# uname -r 
5.10.83-1-lts
# echo test >/dev/stderr #KO
# cat /dev/stderr
test
# echo test >&2 #OK
test
```
regards, lacsaP.

**Comment by patatetom** [comment]
hi,

archlinux has reintroduced `/dev/stderr` and the problem persists with the latest versions of `pv`.

a change introduced after version 1.6.6 is probably at the origin of this strange behavior... (because version 1.6.20 works perfectly in the final system).

regards, lacsaP.

**Comment by a-j-wood** [comment]
A fix for this has been suggested, and has been merged in. It will be in the next release.

**Comment by patatetom** [comment]
thanks a lot
