### ISSUE TITLE
Options to change the units in the rate display

### ISSUE THREAD

**Issue by a-j-wood** [a-j-wood/pv#21]
Date: Tue, 8 Feb 2022 11:47:29 -0800
From: Jeffrey Paul
Subject: pv feature suggestion

Hi there!  I love pv and use it literally every single day, I think it is one of the best unix utilities ever invented.  Thank you so much for making it.

I was looking today for a command line option to specify output rate display in bits/sec instead of bytes/sec (as is convention for network transfer speeds, as I use pv in remote ssh commands frequently to run backups across the network).   I was surprised to see that there isn't one.

This is a feature suggestion for an output modifier command line flag that would cause pv to output its rate display in bits/s instead of bytes/s.

Best,
-sneak

----

Date: Sun, 6 Jan 2019 00:59:14 +0000
From: John W. O'Brien

Hi Andrew,

Thank you for pv. It's a very nice tool.

As a network geek, it would be really swell if pv could display rates in bits per second (or kb or Mb...) using something like the '-l' switch except for bits instead of lines. Would you entertain this as a feature request? Would candidate patches increase the likelihood?

Happy New Year!

----

Date: Mon, 10 Dec 2018 13:32:07 -0500
From: David Henderson ( https://www.cliquesoft.org )
Subject: storage units with pv

Good morning Andrew!  I am using 'pv' with a project and see that the
units appear to be KiB, MiB, etc (x1024).  Some of the values I am
working with use KB, MB, etc (x1000) which throws off the 'pv' meter
output so it doesn't show 100% even though it has processed
everything.  I am using version 1.5.7 and tried both 'm' and 'M'
suffixes to see if 'pv' would use a different measurement based on the
case of the trailing letter, but it does not appear so.  Are their any
plans to add these different values?

Thanks,
Dave

**Comment by aksel** [comment]
I don't know if this is tertiary, but it would be nice to be able to specify the unit as well, e.g. forcing it to always output `-a` as bytes/s.

**Comment by a-j-wood** [comment]
This is covered as far as currently feasible by pull request #63.
