### ISSUE TITLE
Fix compilation problems due to stat64() on Apple Silicon

### ISSUE THREAD

**Issue by a-j-wood** [a-j-wood/pv#33]
Date: Mon, 04 Jan 2021 19:25:25 +0100
From: Filippo Valsorda
Subject: PATCH: make pv compile on Apple Silicon

Since macOS 10.6, stat64 variants are equivalent to plain stat, and the suffixed versions have been removed in macOS 11 (although apparently only running on Apple Silicon).  See stat(2).

diff --git a/src/include/pv-internal.h b/src/include/pv-internal.h
index 46d7496..fed25fe 100644
--- a/src/include/pv-internal.h
+++ b/src/include/pv-internal.h
@@ -18,6 +18,14 @@
 #include <sys/time.h>
 #include <sys/stat.h>

+// Since macOS 10.6, stat64 variants are equivalent to plain stat, and the
+// suffixed versions have been removed in macOS 11. See stat(2).
+#ifdef __APPLE__
+#define stat64 stat
+#define fstat64 fstat
+#define lstat64 lstat
+#endif
+
 #ifdef __cplusplus
 extern "C" {
 #endif

**Comment by demitri** [comment]
That patch worked for me, except to change

```c
#ifdef APPLE
```

to

```c
#if defined(__APPLE__)
```

**Comment by a-j-wood** [comment]
Thanks @FiloSottile and @demitri, changes for this will be in the next release after 1.6.20.
