### ISSUE TITLE
Allow pv to report on a whole pipeline at once

### ISSUE THREAD

**Issue by a-j-wood** [a-j-wood/pv#50]
Date: Fri, 11 Feb 2011 20:58:17 +0000
Sent from: Will Entriken

Would it be possible to reduce the complexity of calling pv by having it look in /proc to see how the processes are connected?

pv cat linux-2.2.20.tar.bz2 | bzcat | gzip -9 > linux-2.2-20.tar.gz

----

Date: Fri, 11 Feb 2011 23:56:13 +0000
From: Andrew Wood
To: Will Entriken

> Would it be possible to reduce the complexity of calling pv by having it
> look in /proc to see how the processes are connected?
>
> pv cat linux-2.2.20.tar.bz2 | bzcat | gzip -9 > linux-2.2-20.tar.gz

That's an interesting idea, but it would be quite complicated - the /proc
interface doesn't show the current position of each file descriptor, at
least not in all kernels, so the best way to make that work would be for PV
to attach to each relevant process in the pipeline, close the relevant file
descriptors, and re-open them so they go through it instead.

I like the idea though. If you can think of a way to get it working please
let me know! In the meantime I will keep it in mind in case I can come up
with anything myself.

**Comment by gerion0** [comment]
I just want to ask the same and found this issue.
Maybe a similar thing is also possible with a simple client/server infrastructure, so for this example:
```
$ cat linux-2.2.20.tar.bz2 | pv --id 1 -w | bzcat | gzip -9 | pv --id 2 -J 1 > linux-2.2-20.tar.gz
ID 1: 0.00 B 0:00:04 [0,00 B/s] [<=>
ID 2: 0.00 B 0:00:04 [0,00 B/s] [<=>
```
with these flags:
```
--id ID : set its own ID to id
-w, --whole : aggregate information from multiple pv processes
-J , --join ID : connect with the given ID and send all output to it
```
(I tried to avoid letters that are already used as options.)

**Comment by a-j-wood** [comment]
The example you describe is already covered with "-c".

I understood this request as for something where PV could be pointed at a whole pipeline and show the progress at the pipe between each process.

So you would run "cat linux-2.2.20.tar.bz2 | bzcat | gzip -9 > linux-2.2-20.tar.gz &" and then "pv %1" or similar, and it would have the same effect as "cat linux-2.2.20.tar.bz2 | pv -c -N cat | bzcat | pv -c -N bzcat | gzip -9 | pv -c -N gzip > linux-2.2-20.tar.gz".  The latter already works today.

**Comment by gerion0** [comment]
Really cool, I should have read the documentation in more detail!

Yeah, I also understood the original request in the way that you described. I though, however, that using multiple pv calls in one pipeline was not possible (which is a workaround to the original request as you also described).

**Comment by a-j-wood** [comment]
This project has moved to Codeberg so the issue is open there instead: https://codeberg.org/a-j-wood/pv/issues/50
