### ISSUE TITLE
Feature Request: Run command every n percent

### ISSUE THREAD

**Issue by haarp** [a-j-wood/pv#54]
Hello,

pv is awesome and I'm using it for diagnostics and other purposes. Thanks for making it!

There's one idea I've been thinking about. What about the ability to run commands at certain percentages? Perferably with formatting support. This would useful for long-running transfers that you can't/don't want to observe, but still want to be able to get pv's stats.

e.g. something like `pv --command="notify-send 'pv' '%p'" --command-interval 25 foo > bar` would show a notification for every 25 percent to completion.
Or `--command="echo -ne '\a'" --command-interval 10` would ring the terminal bell every 10 percent.

Cheers! :)

**Comment by a-j-wood** [comment]
What's the specific use case?  Are you thinking that it would be not running in a terminal, but instead would be sending a desktop notification only?  What would you want it to do if it exited unexpectedly?

What do you think this should do if the percentage doesn't move uniformly?  e.g. if it's to do something every 10%, if we jump from 9% to 11% should it fire, and if we jumped from 12% to 32% should it fire twice?

**Comment by haarp** [comment]
Hey, thanks for answering. My specific use-case is that I use pv in scripts which may run interactively or non-interactively. In the latter case, there's no terminal but I'd still like to follow along the progress.

>  What would you want it to do if it exited unexpectedly?

Personally, I see no need to handle this in pv. This can be handled by whatever script is calling it (and exit codes).

> What do you think this should do if the percentage doesn't move uniformly? e.g. if it's to do something every 10%, if we jump from 9% to 11% should it fire, and if we jumped from 12% to 32% should it fire twice?

So basically whether there should be timeouts to avoid "spammy" commands? This is probably unnecessary work. For notify-send in particular, it's possible to replace a previous notification (if it exists), instead of spawning a new one.

**Comment by a-j-wood** [comment]
This project has moved to Codeberg so the issue is open there instead: https://codeberg.org/a-j-wood/pv/issues/54
