### ISSUE TITLE
pv Stopped Working in the Background

### ISSUE THREAD

**Issue by CraigMiloRogers** [a-j-wood/pv#55]
I have an application that starts a background pv process to generate a progress bar for a complex pipeline.  This used to work as I expected in pv 1.6.6.  It no longer works in pv 1.6.20. pv runs, but the progress bar is not displayed.

In the new routine pv_in_foreground(void), the code does not check for an error return from tcgetpgrp(STDERR_FILENO). 
```
our_process_group = getpgrp(); 
tty_process_group = tcgetpgrp(STDERR_FILENO);                                                                                                             
if (our_process_group == tty_process_group)                                                                                                               
    return true; 
```

Changing the code to the following does what I want:
```
our_process_group = getpgrp();
tty_process_group = tcgetpgrp(STDERR_FILENO);   
if (tty_process_group == -1)
    return true;
if (our_process_group == tty_process_group)                                                                                                               
    return true; 
```

Alternatively, a command line flag to force pv_in_foreground() to always return true would be helpful.

**Comment by a-j-wood** [comment]
A fix for this has been suggested, and has been merged in.  It will be in the next release.
