### ISSUE TITLE
add newline option to pv --format

### ISSUE THREAD

**Issue by diepes** [a-j-wood/pv#58]
**Enhancement request:**

**Additional flag** that **inserts a new line** "\n" in --format string.  e.g. "%n"

**Problem:**
Inserting a newline is hard in bash with crazy quoting rules, trying to use pv to log to file for later investigation
e.g.
cat infile |  pv -i1 -f --format "%t %b %a %r\n"  2>pv-log.txt  |  grep "abc" | gzip > outfile

this results in pv-log.txt with entries with one long string with pv output interspersed with "\n^M".
```0:00:01 3.56MiB [3.54MiB/s]avg [3.54MiB/s]\n^M0:00:02 7.12MiB [3.55MiB/s]avg [3.56MiB/s]\n^M0:00:03 10.7MiB [3.56MiB/s]avg [3.58MiB/s]\n^M```

Would be great if --format had a **%n for newline** eg.
cat infile | pv -i5 -f --format "%t %b %a %r%n" 2>pv-log.txt | grep "abc" | gzip > outfile
to get

```
0:00:01 3.56MiB [3.54MiB/s]avg [3.54MiB/s]
0:00:02 7.12MiB [3.55MiB/s]avg [3.56MiB/s]
0:00:03 10.7MiB [3.56MiB/s]avg [3.58MiB/s]
```

**Hard example:**
# In bash the \n is just printed out, and using $'\n' breaks rest of concatenation.
cmd="cat infile"
cmd="${cmd} |  pv -i1 -f --format $'%t %b %a %r\r\n'  2>pv-log.txt"
cmd="${cmd}  |  grep "abc" | gzip > outfile"
eval "$cmd"

**Comment by diepes** [comment]
Closing as   --format $'%b\n" works good enough for me for now.

**Comment by aksel** [comment]
+1 on this. This would be quite helpful.
