### ISSUE TITLE
[Feature request] Wrap another process to monitor its stdin & stdout

### ISSUE THREAD

**Issue by axman6** [a-j-wood/pv#67]
Something I frequently use `pv` for is monitoring whether compression is useful in a pipeline. I often have something that looks like:

```shell
> ... | pv -N uncomp -c -<flags> | <zstd|lz4|gzip|etc.> -<flags> | pv -N comp -c -<flags> | ...
```

What I would like to see is a new flag, perhaps `-x` for e`x`ecute, which which would look something like this:

```shell
> ... | pv -N comp -c -<flags> -x --  <prog> -<flags> | ...
```

which would fork `prog` and manage and monitor its stdin and stdout. The big benefit of this over two instances of `pv` is it would allow a new flag, perhaps `-z` for "zip", which would show the ratio of data in/data out (with -Z for data out/data in).

In this mode, formatting clearly gets a bit more complicated, since there's now two values that `%r` could reference - for the MVP of this feature, I would leave what there is now and have that apply to stdin or stdout, whichever makes more sense (I'm not sure which, but leaning towards stdin), and at a future data adding `%R`, `%A`, `%B`, `%P`, for the corresponding stdout/stdin metrics (as well as `%z` and `%Z` for the ratios).

I'm hoping to at least open the discussion, and likely be told why this definitely wouldn't work, but keen to hear thoughts on alternative ways to achieve something similar.

This looks like it may be related to #50.

**Comment by a-j-wood** [comment]
It's an interesting idea, I'm hesitant to look into it much because I think it opens up a whole class of potential vulnerabilities or bugs.  I can't see any particular reason why it couldn't work other than it just sounds hard to do!

What sort of use case do you have for this, where you need a live display of the ratio of in to out, rather than looking at file sizes afterwards?

**Comment by axman6** [comment]
The use case I have is wanting to see compression ratios in a pipeline while it's executing, where there may not be an input or output file it all - and example would be using `zfs send | ... | zfs receive` vs `zfs send | compress | .. | decompress | zfs receive` over a network, to see whether there's any benefit in compressing data (if compression/decompression is faster than the network speed, the transfer would finish faster, but if it's not helping, I can stop the transfer and remove the compression steps). 

Generally if I'm compressing something large, it will take a long time, and being able to get an early indication of how well the compression is going is very useful.

I'm not sure how this could lead to any security issues, all that needs to be done is to fork the process (which is exactly as dangerous as being able to run the process already) with its stdin and stdout being a copy of pv's (or if it makes it easier to build the statistics, a new file handle for each, with pv copying from its own stdin, to the process' - I haven't looked at how pv is implemented so I'm not sure what would be easiest). 

Implementing this would likely need to use threads, one for stdin and one for stdout, and then likely a third which manages the printing of output. This would likely comoplicate the architecture of pv, but also open it up to some useful modes in the future. Taking it to the extreme, you'd be able to use pv like a simple shell, where it can report on all the intermediate pipelines:

```shell
> pv - opts -q "zfs send | lz4 | ssh ... 'lz4 -d | zfs receive\'"
zfs send <stats>
lz4      <stats>
ssh      <stats>
```

I'm not suggesting this is is something that should be done, but it would be very cool have, and matches many of my use cases for pv where I end up with nearly every intermediate pipe having a pv instance.

**Comment by a-j-wood** [comment]
Thanks.  The specific example you've given nicely highlights the main problem I expect to have when implementing it.  I would most likely try to effectively insert "`pv <options>`" at every "`|`", so for example, this:

    pv --pipeline -pterb "zfs send | lz4 | ssh destination 'lz4 -d | zfs receive'"

...would be the equivalent of running this:

    zfs send \
    | pv -cN "zfs send" -pterb \
    | lz4 \
    | pv -cN "lz4" -pterb \
    | ssh destination 'lz4 -d | zfs receive' \
    | pv -cN "ssh dest..." -pterb

in which case, pv has to understand shell quoting, so it doesn't make that last one "`ssh destination 'lz4 -d | pv .... | zfs receive'`" and break the SSH command.

The vulnerabilities I'm thinking about revolve around splitting the supplied pipeline into commands correctly, like the shell does, without falling foul of bad input, like filenames in the pipeline that have unexpected characters in them - such as pipe symbols.

It looks like the `wordexp()` C library function might do the job, but that doesn't appear to be available on OpenBSD 7.3, so I don't know how cross-platform this would be.

Potential problems aside - does the description here sound like the way you would expect such a feature to work?

**Comment by axman6** [comment]
I think you've understood the latter part of my comment, but it isn't the feature I'm requesting - all I'm after is the ability to wrap a single process' stdin and stdout, so there's no need to understand the shell escaping, the shell will do that for you. In my example, what I would like to be able to do is:

```shell
> zfs send foo | pv -<pv-flags> -- zstd -<zstd-flags> | ... # this point on is irrelevant
```

All that would be needed, for a MVP anyway, is to fork and execvp (or something similar that can look up the name of the executable passed in as the first argument after `--`). The arguments to this exec call will be exactly the arguments passed to pv's main, with the name of the executable being the first argument after `--`, and the rest of the arguments being the rest of `argv` - something like:

```c
...
// Set up stdin/stdout for child process, so that pv can measure the transfer from the parent 
// into the child, then back out to it's own stdout.

pid_t child = fork();
if(!child) { // we are the child
  int i = 0;
  char * arg;
  while ((arg = argv[i])) {
    if (strcmp(arg, "--") == 0) { // We found the divider
      i++;
      char * progname;
      if ((progname = argv[i]) { // There is a program name
        execvp(progname, argv + i + 1);
      }
    }
    i++;
  }
}
```
(very roughly).

You'd basically end up with two instances of pv (likely in separate threads so they're not blocking each other), one measuring stats from pv-stdin -> child-stdin, and one measuring child-stdout -> pv-stdout, instead of the current pv-stdin -> pv-stdout.

I can't see how there could be any security concerns, as the child process would behave precisely as it would have if pv were not wrapping it - `pv -<flags> -- prog args` is just `prog args` with its stdin/out being monitored, all shell escaping has been handled by the shell and unescaped in `argv`. Does that make sense? 

The example you've mentioned, with passing in a pipeline into pv, is a bluesky idea that would be cool to have, but not something I'm requesting. It's just an example of an idea that would be possible if the functionality for pv to wrap processes existed.

**Comment by a-j-wood** [comment]
Thanks for the explanation.  I definitely picked up the wrong end of the stick there (biased towards #50 and forgot to read your opening comment again, perhaps).

Could we implement a feature like this initially by *just* adding a ratio option, having the pv instances communicate between themselves with IPC?  We'd have to make this ratio option identify the other pv somehow (so they end up in the right order), maybe by name?

So, something like this:

    zfs send foo \
    | pv -cN inputSide -<pv-flags> \
    | zstd -<zstd-flags> \
    | pv -cN outputSide -<pv-flags> -z inputSide:outputSide

and that "`-z`" option would make the "outputSide" pv instance show the ratio of inputSide byte count to outputSide byte count as a percentage - would that make sense?

Keeping it as two pv instances would mean you could give them different options / formats as you see fit.

For convenience, we could *then* add an "execute" option to do the wrapping for you to save some repetition in the simplest use case as per the above - input and output sides would have the same format, except the output side also gets the input/output percentage.

**Comment by a-j-wood** [comment]
This project has moved to Codeberg so the issue is open there instead: https://codeberg.org/a-j-wood/pv/issues/67
