### ISSUE TITLE
Configure issue for stat64

### ISSUE THREAD

**Issue by thesamesam** [a-j-wood/pv#69]
In 1.7.0, config.log has:
```
configure:5210: gcc -c -O  conftest.c >&5
conftest.c: In function 'main':
conftest.c:37:14: warning: implicit declaration of function 'stat64' [-Wimplicit-function-declaration]
   37 | int main() { stat64(); }
      |              ^~~~~~
```

This is going to be a problem with stricter C compilers which will soon (some already do, e.g. Clang 16) make implicit function declarations an error by default. See https://wiki.gentoo.org/wiki/Project:Toolchain/Modern_C_porting.

If we include the right header (`#define _LARGEFILE64_SOURCE` and `#include <sys/stat.h>`) then the configure test will succeed, but i'm not convinced we need this.

I suspect we may be better off ripping out stat64 (and all the rest of it) stuff and using `AC_SYS_LARGEFILE`, then using native `stat` etc everywhere.

**Comment by a-j-wood** [comment]
Large file support seems to be a recurring issue, especially on Mac platforms.  I will look at `AC_SYS_LARGEFILE`, as LFS was added to PV a _very_ long time ago, and as you say, ripping it all out and starting over with just `stat()` everywhere is probably the solution.

**Comment by a-j-wood** [comment]
In the most recent commit, I have removed all stat64 etc calls, and rewritten configure.in and header.in to use AC_SYS_LARGEFILE properly as per the autoconf and autoheader manuals.  Does this build cleanly for you?  I've tried it on CentOS 5, CentOS 7, Debian 12, and OpenBSD 7.3, and it compiles and passes "make test".

I have not yet thought about how to add in tests to make sure it actually works with large files, after these changes - any suggestions would be appreciated.

**Comment by a-j-wood** [comment]
Large file support tests have now been added.

**Comment by thesamesam** [comment]
Thank you! In a few days, I'll give this a spin on a few platforms too. Not had a chance just yet. In particular, we need to make sure everything is fine on 32-bit arches.

**Comment by thesamesam** [comment]
I've been unable to make anything break and it seems to be built + function correctly on 32-bit platforms I've tested. Thank you for handling this so quickly.

**Comment by a-j-wood** [comment]
That's good news - thanks.  I'll close this issue.
