### ISSUE TITLE
new compilation warnings

### ISSUE THREAD

**Issue by anarcat** [a-j-wood/pv#70]
Hello!

I'm working on updating the Debian package from 1.6.20 to 1.7.0 and I am seeing compilation warnings I do not remember seeing before. I have three theories on why that might be new:

 1. I forgot they already existed
 2. Debian (or our gcc version) is stricter than before
 3. some regression was introduced

I tend to believe it's a case 2 here. :) Anyway, here are the warnings. There are two types, one is the `write` return value being ignored, possibly harmless:

```
src/pv/loop.c: In function ‘pv_main_loop’:
src/pv/loop.c:331:25: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  331 |                         write(STDERR_FILENO, "\n", 1);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

the other seems possibly more problematic:

```
src/pv/loop.c:558:28: warning: ‘__builtin_snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
  558 |                         "%s", original_format_string);
      |                            ^
```

here's the full build log from my laptop:  [pv_1.7.0-1_amd64-2023-07-18T02:47:06Z.build.txt](https://github.com/a-j-wood/pv/files/12075432/pv_1.7.0-1_amd64-2023-07-18T02.47.06Z.build.txt)

**Comment by a-j-wood** [comment]
Yes I believe GCC has become stricter.  On CentOS 7 no warnings are shown - but that's GCC 4.8.5, whereas Debian 12 is using GCC 12.2.0.

At the moment I don't think these are a problem but I would like to review all of the sprintf() and snprintf() calls soon in any case.  I'll keep this open until PV compiles without warnings on Debian.

**Comment by anarcat** [comment]
Sounds great!

I wonder: maybe there could be a CI job here (GitHub action?) that
compiles pv and checks for such warnings? Surely something like this
must exist out there... ;)

**Comment by a-j-wood** [comment]
Scripting that would be simple enough, but it would require having a VM of each supported OS or distribution, and PV doesn't really have a list of those.  They'd need hosting somewhere.  Or, I could just write tidier code...

Really I would like to have a thorough session with `splint` and `flawfinder`, and the more recent GCC and Clang compilers, to do some cleaning up.  I keep dropping off the face of the earth, but I will get around to it some day.

**Comment by anarcat** [comment]
On 2023-07-18 13:32:07, Andrew Wood wrote:
> Scripting that would be simple enough, but it would require having a VM of each supported OS or distribution, and PV doesn't really have a list of those.  They'd need hosting somewhere.  Or, I could just write tidier code...

I think GitLab actions can go a long way there...

**Comment by a-j-wood** [comment]
I've committed a few changes now, which I've tested on OpenBSD 7.3, CentOS 5 32-bit, CentOS 6 32 and 64 bit, CentOS 7, AlmaLinux 8-9, OpenSUSE Leap 15.3-15.4, Debian 11, Debian 12 64-bit AMD, and Debian 12 64-bit ARM.  There are no warnings any more, but I think I am using different CFLAGS to you.  Where does your build process pick up its CFLAGS from?

**Comment by anarcat** [comment]
> Where does your build process pick up its CFLAGS from?

I don't remember from the top of my head, but Debian has its own stack of CFLAGS it injects into every build that respects the convention.  I *think* that's managed through [dpkg-buildflags](https://manpages.debian.org/dpkg-buildflags). A blank run of that command here yields this:

```
anarcat@angela:~$ dpkg-buildflags
ASFLAGS=
CFLAGS=-g -O2 -ffile-prefix-map=/home/anarcat=. -fstack-protector-strong -Wformat -Werror=format-security
CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
CXXFLAGS=-g -O2 -ffile-prefix-map=/home/anarcat=. -fstack-protector-strong -Wformat -Werror=format-security
DFLAGS=-frelease
FCFLAGS=-g -O2 -ffile-prefix-map=/home/anarcat=. -fstack-protector-strong
FFLAGS=-g -O2 -ffile-prefix-map=/home/anarcat=. -fstack-protector-strong
GCJFLAGS=-g -O2 -ffile-prefix-map=/home/anarcat=. -fstack-protector-strong
LDFLAGS=-Wl,-z,relro
OBJCFLAGS=-g -O2 -ffile-prefix-map=/home/anarcat=. -fstack-protector-strong -Wformat -Werror=format-security
OBJCXXFLAGS=-g -O2 -ffile-prefix-map=/home/anarcat=. -fstack-protector-strong -Wformat -Werror=format-security
```

That's on Debian bookworm, now the stable release. Unstable might have more stuff added, i can check if you wish. I don't believe my Debian package stuff adds anything on top of that either...

I'll see if your patch fixes the problems here tomorrow.

**Comment by anarcat** [comment]
i'm having trouble compiling from git within the debian package, it's quite a hassle... we typically need a new tarball to package a new release and while there are ways around this, i can't quite figure it out right now, especially since the changes touched the toolchain (autoconf and friends) quite a bit...

so i guess i'll wait until the next release to confirm this!

**Comment by a-j-wood** [comment]
Running "`./generate.sh && ./configure && make dist`" from a git clone should get you a tarball of the same format as a release, but if that doesn't work I hope to get another release out in the next week or two containing a lot of cleanups.

**Comment by a-j-wood** [comment]
Version 1.7.17 is released.

**Comment by thesamesam** [comment]
Debian, Ubuntu, and indeed Gentoo all patch `-D_FORTIFY_SOURCE=2` (and sometimes 3) into the compiler itself, rather than passing it on the command line during builds.

You need F_S to get these warnings (at least the warn-if-unused thing, and very likely the other one too). We should add a CI job with F_S enabled at some point.

**Comment by a-j-wood** [comment]
I've been building and testing 1.7.17 and 1.7.18 on Debian 12 with the above flags (including -D_FORTIFY_SOURCE=2), and it has emitted no warnings, so I hope that this is now resolved.

**Comment by thesamesam** [comment]
Excellent - pardon my interference in that case. For me, it is indeed warning free too. Thanks again for pv.

**Comment by a-j-wood** [comment]
No problem, I appreciate the input.

I'll close this on the basis that I was able to reproduce the warnings originally described, and after the rewrites for 1.7.17 / 1.7.18, using the same build flags produces no warnings.

**Comment by anarcat** [comment]
i can confirm the latest release (1.7.24) builds absolutely cleanly on Debian unstable, congrats! and thanks! :)
