### ISSUE TITLE
Mac OS X: implicit declaration of function 'ioctl' is invalid

### ISSUE THREAD

**Issue by TurtleWilly** [a-j-wood/pv#74]
Building the latest **pv 1.7.24** I encounter this "_implicit declaration of function 'ioctl'_" issue.

```
…
gcc -O -I./src/include -Isrc/include -DHAVE_CONFIG_H -DLOCALEDIR=\"/usr/local/share/locale\" -c -o src/pv/display.o src/pv/display.c
src/pv/display.c:93:12: warning: implicit declaration of function 'ioctl' is invalid in C99 [-Wimplicit-function-declaration]
                if (0 == ioctl(STDERR_FILENO, TIOCGWINSZ, &wsz)) {
                         ^
1 warning generated.
gcc -O -I./src/include -Isrc/include -DHAVE_CONFIG_H -DLOCALEDIR=\"/usr/local/share/locale\" -c -o src/pv/file.o src/pv/file.c
…
```

It looks like _ioctl_ comes from "<sys/ioctl.h>" here, so I can workaround it by passing `CPPFLAGS="-DGWINSZ_IN_SYS_IOCTL"` during _configure_, but it probably should work out of the box. Maybe like this in `src/pv/display.c`:

```
#if defined(GWINSZ_IN_SYS_IOCTL) || defined(__APPLE__)
#include <sys/ioctl.h>
#endif
```

**Comment by a-j-wood** [comment]
Rather than make special exceptions for Apple, I have committed a change which makes the decision about whether to include that header file a bit simpler, since we should probably be including it in most cases anyway.

Can you please try a "`git clone https://github.com/a-j-wood/pv.git`" followed by a "`./generate.sh && ./configure && make`" and see if this has cleared it up?

**Comment by TurtleWilly** [comment]
Looks good to me. Properly seems to detect it during the configure process:

```
…
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
…
```

and then compiles fine w/o any warning:

```
…
gcc -O -I./src/include -Isrc/include -DHAVE_CONFIG_H -DLOCALEDIR=\"/usr/local/share/locale\" -c -o src/pv/cursor.o src/pv/cursor.c
gcc -O -I./src/include -Isrc/include -DHAVE_CONFIG_H -DLOCALEDIR=\"/usr/local/share/locale\" -c -o src/pv/display.o src/pv/display.c
gcc -O -I./src/include -Isrc/include -DHAVE_CONFIG_H -DLOCALEDIR=\"/usr/local/share/locale\" -c -o src/pv/file.o src/pv/file.c
…
```

👍

**Comment by a-j-wood** [comment]
Thank you for the confirmation.  I will close this issue.
